name: daily
on:
  workflow_dispatch: 
  schedule:
    - cron: '00 16 * * *'

jobs:
  run-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
      - name: Fetch data and analyze
        run: ./gradlew run analyze -Dsince=2015-01-01
      - name: Upload analysis CSV
        uses: actions/upload-artifact@v4
        with:
          name: analysis-csv
          path: build/analysis/*.csv
          if-no-files-found: error
